### PR TITLE
run dartfmt -w lib/ test/ to make travis happy

### PR DESCRIPTION
**Pull request by jmolins**
Since Travis was complaining I have run dartfmt to the modified files to make it happy.

### CODE REVIEW

**Comment by jmolins** [comment]
Now, travis does not complain about the formatting anymore.
But it can't load the Chrome browser to run the browser tests.
I recognize that I haven't run ``all_browser_test.dart`` tests before committing, just ``all_test.dart``. I have no experience with dart coding for browser.

**Comment by jmolins** [comment]
Anyway, since you have already uploaded version 0.0.4 to pub, this reformatting can wait for the next version.

**Comment by lejard-h** [comment]
can you run `pub run test -p "chrome" test/all_browser_test.dart` locally ?

**Comment by jmolins** [comment]
Just tried but the test failed.
If I run "pub run test test/all_test.dart" all tests pass.
But with the browser test, I get the output below. I don't know if I miss anything.

D:\Coding\flutter_code\google_maps_webservice>pub run test -p "chrome" test/all_browser_test.dart
00:00 +0: compiling test/all_browser_test.dart
CreateProcessW failed 2
00:00 +0 -1: compiling test/all_browser_test.dart [E]
  Failed to load "test/all_browser_test.dart":
  El sistema no puede encontrar el archivo especificado. (Can't locate file)

    Command: D:\flutter\bin\cache\dart-sdk\bin\dart2js.bat --checked C:\Users\Chema\AppData\Local\Temp\dart_test_40a453b1-418b-11e8-834b-a08869525917\runInBrowser.dart --out=C:\Users\Chema\AppData\Loc
al\Temp\dart_test_40a453af-418b-11e8-834b-a08869525917\test_40a453b0-418b-11e8-834b-a08869525917\all_browser_test.dart.browser_test.dart.js --packages=file:///D:/Coding/flutter_code/google_maps_webser
vice/.packages
  dart:async/future_impl.dart 22                                _Completer.completeError
  dart:io-patch/process_patch.dart 423                          _ProcessImpl._start.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                      new Timer
  dart:async/timer.dart 87                                      Timer.run
  dart:io-patch/process_patch.dart 408                          _ProcessImpl._start
  dart:io-patch/process_patch.dart 36                           Process.start
  package:test/src/runner/compiler_pool.dart 77:37              CompilerPool.compile.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper
  package:test/src/runner/compiler_pool.dart 59:38              CompilerPool.compile.<fn>.<fn>
  package:test/src/util/io.dart 112:36                          withTempDir.<fn>.<fn>
  dart:async/future.dart 222                                    new Future.sync
  package:test/src/util/io.dart 112:16                          withTempDir.<fn>
  dart:async/future.dart 222                                    new Future.sync
  package:test/src/util/io.dart 110:14                          withTempDir
  package:test/src/runner/compiler_pool.dart 59:14              CompilerPool.compile.<fn>
  dart:async/future.dart 222                                    new Future.sync
  package:pool/pool.dart 126:18                                 Pool.withResource.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134                                     _rootRunUnary
  dart:async/zone.dart 1031                                     _CustomZone.runUnary
  dart:async/future_impl.dart 129                               _FutureListener.handleValue
  dart:async/future_impl.dart 633                               Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 662                               Future._propagateToListeners
  dart:async/future_impl.dart 477                               Future._completeWithValue
  dart:async/future_impl.dart 507                               Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113        _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 238                               Future.then
  package:pool/pool.dart 125:22                                 Pool.withResource
  package:test/src/runner/compiler_pool.dart 56:18              CompilerPool.compile
  package:test/src/runner/browser/platform.dart 363:24          BrowserPlatform._compileSuite.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/runner/browser/platform.dart 359:59          BrowserPlatform._compileSuite.<fn>
  dart:collection-patch/dart:collection/compact_hash.dart 277   _HashVMBase&MapMixin&&_LinkedHashMapMixin.putIfAbsent
  package:test/src/runner/browser/platform.dart 359:28          BrowserPlatform._compileSuite
  package:test/src/runner/browser/platform.dart 264:17          BrowserPlatform.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/runner/browser/platform.dart 219:61          BrowserPlatform.load
  package:test/src/runner/loader.dart 252:36                    Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055                                     _CustomZone.registerUnaryCallback
  dart:async-patch/dart:async/async_patch.dart 77               _asyncThenWrapperHelper
  package:test/src/runner/loader.dart 246:68                    Loader.loadFile.<fn>
  package:test/src/runner/load_suite.dart 89:31                 new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/runner/load_suite.dart 88:23                 new LoadSuite.<fn>.<fn>
  package:test/src/utils.dart 297:5                             invoke
  package:test/src/runner/load_suite.dart 88:7                  new LoadSuite.<fn>
  package:test/src/backend/invoker.dart 403:25                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 402:31                  Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 174                                    new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 925                                      _CustomZone.runGuarded
  dart:async/zone.dart 965                                      _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async-patch/dart:async/timer_patch.dart 21               Timer._createTimer.<fn>
  dart:isolate-patch/dart:isolate/timer_impl.dart 382           _Timer._runTimers
  dart:isolate-patch/dart:isolate/timer_impl.dart 416           _Timer._handleMessage
  dart:isolate-patch/dart:isolate/isolate_patch.dart 165        _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52                                      new Timer
  dart:async/timer.dart 87                                      Timer.run
  dart:async/future.dart 172                                    new Future
  package:test/src/backend/invoker.dart 402:15                  Invoker._onRun.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047                                     _CustomZone.registerCallback
  dart:async/zone.dart 964                                      _CustomZone.bindCallbackGuarded
  dart:async/schedule_microtask.dart 147                        scheduleMicrotask
  dart:async/future.dart 198                                    new Future.microtask
  package:test/src/backend/invoker.dart 389:27                  Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 389:9                   Invoker._onRun.<fn>.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:test/src/backend/invoker.dart 144:7                   Invoker.guard
  package:test/src/backend/invoker.dart 441:15                  Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 388:7                   Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 1501                                     runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test/src/backend/invoker.dart 387:11                  Invoker._onRun
  package:test/src/backend/live_test_controller.dart 188:11     LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31      _LiveTest.run
  dart:async/future.dart 200                                    new Future.microtask.<fn>
  dart:async/zone.dart 1126                                     _rootRun
  dart:async/zone.dart 1023                                     _CustomZone.run
  dart:async/zone.dart 949                                      _CustomZone.bindCallback.<fn>
  dart:async/schedule_microtask.dart 41                         _microtaskLoop
  dart:async/schedule_microtask.dart 50                         _startMicrotaskLoop
  dart:isolate-patch/dart:isolate/isolate_patch.dart 113        _runPendingImmediateCallback
  dart:isolate-patch/dart:isolate/isolate_patch.dart 166        _RawReceivePortImpl._handleMessage

00:00 +0 -1: Some tests failed.

**Comment by lejard-h** [comment]
will accept and try to repair travis later

**Pull request merged**
